services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'milestone-services'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3309:3306'
    expose:
      # Opens port 3306 on the container
      - '3309'
      # Where our data will be persisted
    volumes:
      - data:/var/lib/mysql
volumes:
  data:


